
CREATE TABLE states (
    id INT PRIMARY KEY,
    state_name VARCHAR(50)
);

INSERT INTO states(id,state_name) VALUES (1,'Abia');
INSERT INTO states(id,state_name) VALUES (2,'Adamawa');
INSERT INTO states(id,state_name) VALUES (3,'Akwa Ibom');
INSERT INTO states(id,state_name) VALUES (4,'Anambra');
INSERT INTO states(id,state_name) VALUES (5,'Bauchi');
INSERT INTO states(id,state_name) VALUES (6,'Bayelsa');
INSERT INTO states(id,state_name) VALUES (7,'Benue');
INSERT INTO states(id,state_name) VALUES (8,'Borno');
INSERT INTO states(id,state_name) VALUES (9,'Cross River');
INSERT INTO states(id,state_name) VALUES (10,'Delta');
INSERT INTO states(id,state_name) VALUES (11,'Ebonyi');
INSERT INTO states(id,state_name) VALUES (12,'Edo');
INSERT INTO states(id,state_name) VALUES (13,'Ekiti');
INSERT INTO states(id,state_name) VALUES (14,'Enugu');
INSERT INTO states(id,state_name) VALUES (15,'FCT Abuja');
INSERT INTO states(id,state_name) VALUES (16,'Gombe');
INSERT INTO states(id,state_name) VALUES (17,'Imo');
INSERT INTO states(id,state_name) VALUES (18,'Jigawa');
INSERT INTO states(id,state_name) VALUES (19,'Kaduna');
INSERT INTO states(id,state_name) VALUES (20,'Kano');
INSERT INTO states(id,state_name) VALUES (21,'Katsina');
INSERT INTO states(id,state_name) VALUES (22,'Kebbi');
INSERT INTO states(id,state_name) VALUES (23,'Kogi');
INSERT INTO states(id,state_name) VALUES (24,'Kwara');
INSERT INTO states(id,state_name) VALUES (25,'Lagos');
INSERT INTO states(id,state_name) VALUES (26,'Nasarawa');
INSERT INTO states(id,state_name) VALUES (27,'Niger');
INSERT INTO states(id,state_name) VALUES (28,'Ogun');
INSERT INTO states(id,state_name) VALUES (29,'Ondo');
INSERT INTO states(id,state_name) VALUES (30,'Osun');
INSERT INTO states(id,state_name) VALUES (31,'Oyo');
INSERT INTO states(id,state_name) VALUES (32,'Plateau');
INSERT INTO states(id,state_name) VALUES (33,'Rivers');
INSERT INTO states(id,state_name) VALUES (34,'Sokoto');
INSERT INTO states(id,state_name) VALUES (35,'Taraba');
INSERT INTO states(id,state_name) VALUES (36,'Yobe');
INSERT INTO states(id,state_name) VALUES (37,'Zamfara');



CREATE TABLE lgas (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	lga_name TEXT,
    state_name TEXT,
	state_id INTEGER,
	FOREIGN KEY (state_id) REFERENCES states(id)
);


INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (1,'Aba North','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (2,'Aba South','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (3,'Arochukwu','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (4,'Bende','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (5,'Ikwuano','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (6,'Isiala Ngwa North','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (7,'Isiala Ngwa South','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (8,'Isuikwuato','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (9,'Obi Ngwa','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (10,'Ohafia','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (11,'Osisioma','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (12,'Ugwunagbo','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (13,'Ukwa East','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (14,'Ukwa West','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (15,'Umuahia North','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (16,'Umuahia South','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (17,'Umu Nneochi','Abia',1);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (18,'Demsa','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (19,'Fufure','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (20,'Ganye','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (21,'Gayuk','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (22,'Gombi','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (23,'Grie','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (24,'Hong','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (25,'Jada','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (26,'Lamurde','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (27,'Madagali','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (28,'Maiha','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (29,'Mayo Belwa','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (30,'Michika','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (31,'Mubi North','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (32,'Mubi South','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (33,'Numan','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (34,'Shelleng','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (35,'Song','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (36,'Toungo','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (37,'Yola North','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (38,'Yola South','Adamawa',2);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (39,'Abak','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (40,'Eastern Obolo','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (41,'Eket','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (42,'Esit Eket','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (43,'Essien Udim','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (44,'Etim Ekpo','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (45,'Etinan','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (46,'Ibeno','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (47,'Ibesikpo Asutan','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (48,'Ibiono-Ibom','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (49,'Ika','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (50,'Ikono','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (51,'Ikot Abasi','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (52,'Ikot Ekpene','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (53,'Ini','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (54,'Itu','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (55,'Mbo','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (56,'Mkpat-Enin','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (57,'Nsit-Atai','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (58,'Nsit-Ibom','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (59,'Nsit-Ubium','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (60,'Obot Akara','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (61,'Okobo','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (62,'Onna','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (63,'Oron','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (64,'Oruk Anam','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (65,'Udung-Uko','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (66,'Ukanafun','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (67,'Uruan','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (68,'Urue-Offong/Oruko','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (69,'Uyo','Akwa Ibom',3);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (70,'Aguata','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (71,'Anambra East','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (72,'Anambra West','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (73,'Anaocha','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (74,'Awka North','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (75,'Awka South','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (76,'Ayamelum','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (77,'Dunukofia','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (78,'Ekwusigo','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (79,'Idemili North','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (80,'Idemili South','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (81,'Ihiala','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (82,'Njikoka','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (83,'Nnewi North','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (84,'Nnewi South','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (85,'Ogbaru','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (86,'Onitsha North','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (87,'Onitsha South','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (88,'Orumba North','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (89,'Orumba South','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (90,'Oyi','Anambra',4);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (91,'Alkaleri','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (92,'Bauchi','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (93,'Bogoro','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (94,'Damban','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (95,'Darazo','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (96,'Dass','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (97,'Gamawa','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (98,'Ganjuwa','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (99,'Giade','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (100,'Itas/Gadau','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (101,'Jama''are','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (102,'Katagum','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (103,'Kirfi','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (104,'Misau','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (105,'Ningi','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (106,'Shira','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (107,'Tafawa Balewa','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (108,'Toro','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (109,'Warji','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (110,'Zaki','Bauchi',5);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (111,'Brass','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (112,'Ekeremor','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (113,'Kolokuma/Opokuma','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (114,'Nembe','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (115,'Ogbia','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (116,'Sagbama','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (117,'Southern Ijaw','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (118,'Yenagoa','Bayelsa',6);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (119,'Agatu','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (120,'Apa','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (121,'Ado','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (122,'Buruku','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (123,'Gboko','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (124,'Guma','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (125,'Gwer East','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (126,'Gwer West','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (127,'Katsina-Ala','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (128,'Konshisha','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (129,'Kwande','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (130,'Logo','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (131,'Makurdi','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (132,'Obi','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (133,'Ogbadibo','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (134,'Ohimini','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (135,'Oju','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (136,'Okpokwu','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (137,'Oturkpo','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (138,'Tarka','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (139,'Ukum','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (140,'Ushongo','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (141,'Vandeikya','Benue',7);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (142,'Abadam','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (143,'Askira/Uba','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (144,'Bama','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (145,'Bayo','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (146,'Biu','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (147,'Chibok','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (148,'Damboa','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (149,'Dikwa','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (150,'Gubio','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (151,'Guzamala','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (152,'Gwoza','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (153,'Hawul','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (154,'Jere','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (155,'Kaga','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (156,'Kala/Balge','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (157,'Konduga','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (158,'Kukawa','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (159,'Kwaya Kusar','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (160,'Mafa','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (161,'Magumeri','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (162,'Maiduguri','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (163,'Marte','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (164,'Mobbar','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (165,'Monguno','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (166,'Ngala','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (167,'Nganzai','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (168,'Shani','Borno',8);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (169,'Abi','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (170,'Akamkpa','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (171,'Akpabuyo','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (172,'Bakassi','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (173,'Bekwarra','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (174,'Biase','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (175,'Boki','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (176,'Calabar Municipal','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (177,'Calabar South','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (178,'Etung','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (179,'Ikom','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (180,'Obanliku','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (181,'Obubra','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (182,'Obudu','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (183,'Odukpani','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (184,'Ogoja','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (185,'Yakuur','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (186,'Yala','Cross River',9);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (187,'Aniocha North','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (188,'Aniocha South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (189,'Bomadi','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (190,'Burutu','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (191,'Ethiope East','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (192,'Ethiope West','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (193,'Ika North East','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (194,'Ika South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (195,'Isoko North','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (196,'Isoko South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (197,'Ndokwa East','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (198,'Ndokwa West','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (199,'Okpe','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (200,'Oshimili North','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (201,'Oshimili South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (202,'Patani','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (203,'Sapele','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (204,'Udu','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (205,'Ughelli North','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (206,'Ughelli South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (207,'Ukwuani','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (208,'Uvwie','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (209,'Warri North','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (210,'Warri South','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (211,'Warri South West','Delta',10);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (212,'Abakaliki','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (213,'Afikpo North','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (214,'Afikpo South','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (215,'Ebonyi','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (216,'Ezza North','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (217,'Ezza South','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (218,'Ikwo','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (219,'Ishielu','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (220,'Ivo','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (221,'Izzi','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (222,'Ohaozara','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (223,'Ohaukwu','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (224,'Onicha','Ebonyi',11);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (225,'Akoko-Edo','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (226,'Egor','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (227,'Esan Central','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (228,'Esan North-East','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (229,'Esan South-East','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (230,'Esan West','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (231,'Etsako Central','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (232,'Etsako East','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (233,'Etsako West','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (234,'Igueben','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (235,'Ikpoba Okha','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (236,'Orhionmwon','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (237,'Oredo','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (238,'Ovia North-East','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (239,'Ovia South-West','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (240,'Owan East','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (241,'Owan West','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (242,'Uhunmwonde','Edo',12);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (243,'Ado Ekiti','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (244,'Efon','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (245,'Ekiti East','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (246,'Ekiti South-West','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (247,'Ekiti West','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (248,'Emure','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (249,'Gbonyin','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (250,'Ido Osi','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (251,'Ijero','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (252,'Ikere','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (253,'Ikole','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (254,'Ilejemeje','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (255,'Irepodun/Ifelodun','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (256,'Ise/Orun','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (257,'Moba','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (258,'Oye','Ekiti',13);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (259,'Aninri','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (260,'Awgu','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (261,'Enugu East','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (262,'Enugu North','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (263,'Enugu South','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (264,'Ezeagu','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (265,'Igbo Etiti','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (266,'Igbo Eze North','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (267,'Igbo Eze South','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (268,'Isi Uzo','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (269,'Nkanu East','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (270,'Nkanu West','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (271,'Nsukka','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (272,'Oji River','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (273,'Udenu','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (274,'Udi','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (275,'Uzo Uwani','Enugu',14);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (276,'Abaji','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (277,'Bwari','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (278,'Gwagwalada','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (279,'Kuje','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (280,'Kwali','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (281,'Municipal Area Council','FCT',15);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (282,'Akko','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (283,'Balanga','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (284,'Billiri','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (285,'Dukku','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (286,'Funakaye','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (287,'Gombe','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (288,'Kaltungo','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (289,'Kwami','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (290,'Nafada','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (291,'Shongom','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (292,'Yamaltu/Deba','Gombe',16);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (293,'Aboh Mbaise','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (294,'Ahiazu Mbaise','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (295,'Ehime Mbano','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (296,'Ezinihitte','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (297,'Ideato North','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (298,'Ideato South','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (299,'Ihitte/Uboma','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (300,'Ikeduru','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (301,'Isiala Mbano','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (302,'Isu','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (303,'Mbaitoli','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (304,'Ngor Okpala','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (305,'Njaba','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (306,'Nkwerre','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (307,'Nwangele','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (308,'Obowo','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (309,'Oguta','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (310,'Ohaji/Egbema','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (311,'Okigwe','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (312,'Orlu','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (313,'Orsu','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (314,'Oru East','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (315,'Oru West','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (316,'Owerri Municipal','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (317,'Owerri North','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (318,'Owerri West','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (319,'Unuimo','Imo',17);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (320,'Auyo','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (321,'Babura','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (322,'Biriniwa','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (323,'Birnin Kudu','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (324,'Buji','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (325,'Dutse','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (326,'Gagarawa','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (327,'Garki','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (328,'Gumel','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (329,'Guri','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (330,'Gwaram','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (331,'Gwiwa','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (332,'Hadejia','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (333,'Jahun','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (334,'Kafin Hausa','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (335,'Kazaure','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (336,'Kiri Kasama','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (337,'Kiyawa','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (338,'Kaugama','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (339,'Maigatari','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (340,'Malam Madori','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (341,'Miga','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (342,'Ringim','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (343,'Roni','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (344,'Sule Tankarkar','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (345,'Taura','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (346,'Yankwashi','Jigawa',18);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (347,'Birnin Gwari','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (348,'Chikun','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (349,'Giwa','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (350,'Igabi','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (351,'Ikara','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (352,'Jaba','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (353,'Jema''a','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (354,'Kachia','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (355,'Kaduna North','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (356,'Kaduna South','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (357,'Kagarko','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (358,'Kajuru','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (359,'Kaura','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (360,'Kauru','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (361,'Kubau','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (362,'Kudan','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (363,'Lere','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (364,'Makarfi','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (365,'Sabon Gari','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (366,'Sanga','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (367,'Soba','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (368,'Zangon Kataf','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (369,'Zaria','Kaduna',19);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (370,'Ajingi','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (371,'Albasu','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (372,'Bagwai','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (373,'Bebeji','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (374,'Bichi','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (375,'Bunkure','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (376,'Dala','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (377,'Dambatta','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (378,'Dawakin Kudu','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (379,'Dawakin Tofa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (380,'Doguwa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (381,'Fagge','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (382,'Gabasawa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (383,'Garko','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (384,'Garun Mallam','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (385,'Gaya','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (386,'Gezawa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (387,'Gwale','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (388,'Gwarzo','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (389,'Kabo','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (390,'Kano Municipal','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (391,'Karaye','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (392,'Kibiya','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (393,'Kiru','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (394,'Kumbotso','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (395,'Kunchi','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (396,'Kura','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (397,'Madobi','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (398,'Makoda','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (399,'Minjibir','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (400,'Nasarawa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (401,'Rano','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (402,'Rimin Gado','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (403,'Rogo','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (404,'Shanono','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (405,'Sumaila','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (406,'Takai','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (407,'Tarauni','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (408,'Tofa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (409,'Tsanyawa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (410,'Tudun Wada','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (411,'Ungogo','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (412,'Warawa','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (413,'Wudil','Kano',20);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (414,'Bakori','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (415,'Batagarawa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (416,'Batsari','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (417,'Baure','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (418,'Bindawa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (419,'Charanchi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (420,'Dandume','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (421,'Danja','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (422,'Dan Musa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (423,'Daura','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (424,'Dutsi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (425,'Dutsin Ma','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (426,'Faskari','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (427,'Funtua','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (428,'Ingawa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (429,'Jibia','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (430,'Kafur','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (431,'Kaita','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (432,'Kankara','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (433,'Kankia','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (434,'Katsina','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (435,'Kurfi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (436,'Kusada','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (437,'Mai''Adua','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (438,'Malumfashi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (439,'Mani','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (440,'Mashi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (441,'Matazu','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (442,'Musawa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (443,'Rimi','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (444,'Sabuwa','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (445,'Safana','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (446,'Sandamu','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (447,'Zango','Katsina',21);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (448,'Aleiro','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (449,'Arewa Dandi','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (450,'Argungu','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (451,'Augie','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (452,'Bagudo','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (453,'Birnin Kebbi','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (454,'Bunza','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (455,'Dandi','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (456,'Fakai','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (457,'Gwandu','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (458,'Jega','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (459,'Kalgo','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (460,'Koko/Besse','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (461,'Maiyama','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (462,'Ngaski','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (463,'Sakaba','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (464,'Shanga','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (465,'Suru','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (466,'Wasagu/Danko','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (467,'Yauri','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (468,'Zuru','Kebbi',22);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (469,'Adavi','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (470,'Ajaokuta','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (471,'Ankpa','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (472,'Bassa','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (473,'Dekina','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (474,'Ibaji','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (475,'Idah','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (476,'Igalamela Odolu','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (477,'Ijumu','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (478,'Kabba/Bunu','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (479,'Kogi','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (480,'Lokoja','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (481,'Mopa Muro','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (482,'Ofu','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (483,'Ogori/Magongo','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (484,'Okehi','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (485,'Okene','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (486,'Olamaboro','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (487,'Omala','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (488,'Yagba East','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (489,'Yagba West','Kogi',23);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (490,'Asa','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (491,'Baruten','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (492,'Edu','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (493,'Ekiti','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (494,'Ifelodun','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (495,'Ilorin East','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (496,'Ilorin South','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (497,'Ilorin West','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (498,'Irepodun','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (499,'Isin','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (500,'Kaiama','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (501,'Moro','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (502,'Offa','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (503,'Oke Ero','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (504,'Oyun','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (505,'Pategi','Kwara',24);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (506,'Agege','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (507,'Ajeromi-Ifelodun','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (508,'Alimosho','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (509,'Amuwo-Odofin','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (510,'Apapa','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (511,'Badagry','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (512,'Epe','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (513,'Eti Osa','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (514,'Ibeju-Lekki','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (515,'Ifako-Ijaiye','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (516,'Ikeja','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (517,'Ikorodu','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (518,'Kosofe','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (519,'Lagos Island','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (520,'Lagos Mainland','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (521,'Mushin','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (522,'Ojo','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (523,'Oshodi-Isolo','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (524,'Shomolu','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (525,'Surulere','Lagos',25);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (526,'Akwanga','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (527,'Awe','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (528,'Doma','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (529,'Karu','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (530,'Keana','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (531,'Keffi','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (532,'Kokona','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (533,'Lafia','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (534,'Nasarawa','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (535,'Nasarawa Egon','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (536,'Obi','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (537,'Toto','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (538,'Wamba','Nasarawa',26);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (539,'Agaie','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (540,'Agwara','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (541,'Bida','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (542,'Borgu','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (543,'Bosso','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (544,'Chanchaga','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (545,'Edati','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (546,'Gbako','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (547,'Gurara','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (548,'Katcha','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (549,'Kontagora','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (550,'Lapai','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (551,'Lavun','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (552,'Magama','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (553,'Mariga','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (554,'Mashegu','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (555,'Mokwa','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (556,'Moya','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (557,'Paikoro','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (558,'Rafi','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (559,'Rijau','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (560,'Shiroro','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (561,'Suleja','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (562,'Tafa','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (563,'Wushishi','Niger',27);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (564,'Abeokuta North','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (565,'Abeokuta South','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (566,'Ado-Odo/Ota','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (567,'Egbado North','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (568,'Egbado South','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (569,'Ewekoro','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (570,'Ifo','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (571,'Ijebu East','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (572,'Ijebu North','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (573,'Ijebu North East','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (574,'Ijebu Ode','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (575,'Ikenne','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (576,'Imeko Afon','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (577,'Ipokia','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (578,'Obafemi Owode','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (579,'Odeda','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (580,'Odogbolu','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (581,'Ogun Waterside','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (582,'Remo North','Ogun',28);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (583,'Shagamu','Ogun',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (584,'Akoko North-East','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (585,'Akoko North-West','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (586,'Akoko South-West','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (587,'Akoko South-East','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (588,'Akure North','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (589,'Akure South','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (590,'Ese Odo','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (591,'Idanre','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (592,'Ifedore','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (593,'Ilaje','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (594,'Ile Oluji/Okeigbo','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (595,'Irele','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (596,'Odigbo','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (597,'Okitipupa','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (598,'Ondo East','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (599,'Ondo West','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (600,'Ose','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (601,'Owo','Ondo',29);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (602,'Atakunmosa East','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (603,'Atakunmosa West','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (604,'Aiyedaade','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (605,'Aiyedire','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (606,'Boluwaduro','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (607,'Boripe','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (608,'Ede North','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (609,'Ede South','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (610,'Ife Central','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (611,'Ife East','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (612,'Ife North','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (613,'Ife South','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (614,'Egbedore','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (615,'Ejigbo','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (616,'Ifedayo','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (617,'Ifelodun','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (618,'Ila','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (619,'Ilesa East','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (620,'Ilesa West','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (621,'Irepodun','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (622,'Irewole','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (623,'Isokan','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (624,'Iwo','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (625,'Obokun','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (626,'Odo Otin','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (627,'Ola Oluwa','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (628,'Olorunda','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (629,'Oriade','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (630,'Orolu','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (631,'Osogbo','Osun',30);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (632,'Afijio','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (633,'Akinyele','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (634,'Atiba','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (635,'Atisbo','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (636,'Egbeda','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (637,'Ibadan North','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (638,'Ibadan North-East','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (639,'Ibadan North-West','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (640,'Ibadan South-East','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (641,'Ibadan South-West','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (642,'Ibarapa Central','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (643,'Ibarapa East','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (644,'Ibarapa North','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (645,'Ido','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (646,'Irepo','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (647,'Iseyin','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (648,'Itesiwaju','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (649,'Iwajowa','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (650,'Kajola','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (651,'Lagelu','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (652,'Ogbomosho North','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (653,'Ogbomosho South','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (654,'Ogo Oluwa','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (655,'Olorunsogo','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (656,'Oluyole','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (657,'Ona Ara','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (658,'Orelope','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (659,'Ori Ire','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (660,'Oyo','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (661,'Oyo East','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (662,'Saki East','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (663,'Saki West','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (664,'Surulere','Oyo',31);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (665,'Bokkos','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (666,'Barkin Ladi','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (667,'Bassa','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (668,'Jos East','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (669,'Jos North','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (670,'Jos South','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (671,'Kanam','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (672,'Kanke','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (673,'Langtang South','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (674,'Langtang North','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (675,'Mangu','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (676,'Mikang','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (677,'Pankshin','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (678,'Qua''an Pan','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (679,'Riyom','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (680,'Shendam','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (681,'Wase','Plateau',32);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (682,'Abua/Odual','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (683,'Ahoada East','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (684,'Ahoada West','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (685,'Akuku-Toru','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (686,'Andoni','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (687,'Asari-Toru','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (688,'Bonny','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (689,'Degema','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (690,'Eleme','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (691,'Emuoha','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (692,'Etche','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (693,'Gokana','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (694,'Ikwerre','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (695,'Khana','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (696,'Obio/Akpor','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (697,'Ogba/Egbema/Ndoni','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (698,'Ogu/Bolo','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (699,'Okrika','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (700,'Omuma','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (701,'Opobo/Nkoro','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (702,'Oyigbo','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (703,'Port Harcourt','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (704,'Tai','Rivers',33);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (705,'Binji','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (706,'Bodinga','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (707,'Dange Shuni','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (708,'Gada','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (709,'Goronyo','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (710,'Gudu','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (711,'Gwadabawa','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (712,'Illela','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (713,'Isa','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (714,'Kebbe','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (715,'Kware','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (716,'Rabah','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (717,'Sabon Birni','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (718,'Shagari','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (719,'Silame','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (720,'Sokoto North','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (721,'Sokoto South','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (722,'Tambuwal','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (723,'Tangaza','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (724,'Tureta','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (725,'Wamako','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (726,'Wurno','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (727,'Yabo','Sokoto',34);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (728,'Ardo Kola','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (729,'Bali','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (730,'Donga','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (731,'Gashaka','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (732,'Gassol','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (733,'Ibi','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (734,'Jalingo','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (735,'Karim Lamido','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (736,'Kumi','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (737,'Lau','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (738,'Sardauna','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (739,'Takum','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (740,'Ussa','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (741,'Wukari','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (742,'Yorro','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (743,'Zing','Taraba',35);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (744,'Bade','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (745,'Bursari','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (746,'Damaturu','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (747,'Fika','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (748,'Fune','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (749,'Geidam','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (750,'Gujba','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (751,'Gulani','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (752,'Jakusko','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (753,'Karasuwa','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (754,'Machina','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (755,'Nangere','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (756,'Nguru','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (757,'Potiskum','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (758,'Tarmuwa','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (759,'Yunusari','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (760,'Yusufari','Yobe',36);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (761,'Anka','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (762,'Bakura','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (763,'Birnin Magaji/Kiyaw','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (764,'Bukkuyum','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (765,'Bungudu','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (766,'Gummi','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (767,'Gusau','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (768,'Kaura Namoda','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (769,'Maradun','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (770,'Maru','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (771,'Shinkafi','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (772,'Talata Mafara','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (773,'Chafe','Zamfara',37);
INSERT INTO lgas(id,lga_name,state_name,state_id) VALUES (774,'Zurmi','Zamfara',37);


CREATE TABLE wards (
    id INT PRIMARY KEY AUTO_INCREMENT,
    ward_id INT NOT NULL,
    ward_name VARCHAR(255) NOT NULL, 
    lga_id INT NOT NULL, 
    state_id INT NOT NULL, 
    FOREIGN KEY (lga_id) REFERENCES lgas(id), 
    FOREIGN KEY (state_id) REFERENCES states(id)
);


CREATE TABLE transcribed (
    id INT PRIMARY KEY AUTO_INCREMENT,
    state TEXT NOT NULL,
    lga TEXT NOT NULL,
    ward TEXT NOT NULL,
    pu_code TEXT NOT NULL,
    registered_voters INT NOT NULL,
    accredited_voters INT NOT NULL,
    mutilated BOOLEAN NOT NULL,
    is_result_sheet BOOLEAN NOT NULL,
    is_stamped BOOLEAN NOT NULL,
    APC INT NOT NULL,
    APC_agent_signed BOOLEAN NOT NULL,
    LP INT NOT NULL,
    LP_agent_signed BOOLEAN NOT NULL,
    PDP INT NOT NULL,
    PDP_agent_signed BOOLEAN NOT NULL,
    NNPP INT NOT NULL,
    NNPP_agent_signed BOOLEAN NOT NULL,
    result_file_url TEXT NOT NULL,
    username TEXT NOT NULL
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username TEXT UNIQUE,
    password TEXT,
    email TEXT UNIQUE,
    joined_at INTEGER
);

CREATE TABLE reset_password (
    email VARCHAR(255) NOT NULL,
    link VARCHAR(32) NOT NULL,
    expiration_time INTEGER NOT NULL
);